### PR TITLE
LENS-1950 Fix private packages with a package-lock

### PR DESCRIPTION
**Pull request by alanclarke**
Addresses https://github.com/QubitProducts/qubit-cli/pull/455

### CODE REVIEW

**Comment by BenKandelaars** [comment]
Not sure if I'm missing some of the mechanics here. I understand that the repo will now dynamically create a new package-lock.json based on the public dependencies only lock file whenever we publish. I think this will create a fresh dependency tree for the private packages whenever we deploy.

**Comment by BenKandelaars** [comment]
Do we want to still derive a new public + private package-lock.json file but deploy on a precomputed copy. Leaving updates to a dedicated commit.

**Comment by alanclarke** [comment]
@BenKandelaars ok i'll remove the prepublishOnly step

**Comment by alanclarke** [comment]
@BenKandelaars however for the record this is still preferably to not having any transient dependencies locking on install

**Review by BenKandelaars — APPROVED** [review]

**Pull request merged**
